spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productos_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ms_products: INFO
    org.springframework: WARN